# Generated by Django 4.2 on 2023-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
